### PR TITLE
✨  getFile/putFile with options

### PR DESCRIPTION
**Pull request by kirrg001**
no issue

- sftp supports options e.g. opts.step to receive a progress of a downloaded or uploaded file

### CODE REVIEW

**Comment by steelbrain** [comment]
Thanks @kirrg001 

Can you also update README?

**Comment by kirrg001** [comment]
Updated 👍

**Comment by steelbrain** [comment]
Thank You :+1:

**Comment by steelbrain** [comment]
Published in 4.1.0 along with sftp `opts` support in `putFiles` and `putDirectory`

**Pull request merged**
