### PR TITLE
#399 Added Promise rejection on error event.

### PR DESCRIPTION
**Pull request by jackpap**
Hi @steelbrain please check this solution to #399

### CODE REVIEW

**Comment by steelbrain** [comment]
Hi @jackpap 

Thank you for opening this PR! Can you please run this command and commit the changes? Your branch currently has some prettier style differences and that's breaking the CI.

```sh
npx prettier --write src/index.ts
# or if you use Yarn
yarn prettier --write src/index.ts
```

Please leave a comment once you do, so I may get notified and re-review this PR. Thank you!

**Comment by jackpap** [comment]
@steelbrain it's done - please check.

**Comment by steelbrain** [comment]
Thank you for your work here @jackpap!

**Comment by steelbrain** [comment]
Published in node-ssh@12.0.3

**Pull request merged**
