### PR TITLE
Export types/classes/interfaces for Typescript typing

### PR DESCRIPTION
**Pull request by mateussilva92**
I've exported all interfaces, types and classes that should be visible from the outside.

This will help Typescript developers by providing typings for most of function inputs.

### CODE REVIEW

**Comment by steelbrain** [comment]
This would have to be a semver major change, sadly

**Comment by steelbrain** [comment]
@mateussilva92 Thoughts on exporting these from a new file `node-ssh/types`, so we can release this in semver-minor and without breaking for existing users?

**Comment by mateussilva92** [comment]
That can be a solution, I'll update the PR.

**Comment by mateussilva92** [comment]
I mean, we have another solution, since the only thing that is causing problems for the semver major version is the NodeSSH import I can export it as default and that will not cause any problems regarding the current usage of the package.

**Comment by steelbrain** [comment]
Thanks for updating @mateussilva92, this still breaks semver :)
CommonJS imports have to be renamed from `const NodeSSH = require('node-ssh')` to `const {default: NodeSSH} = require('node-ssh')`

but I think it's an acceptable trade-off, this path will eventually lead us down to publishing an esm version as well

**Pull request merged**
